language: node_js
node_js:
- '14'
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: kUK+6SFTiCkntHoUKz5C5QGxWnIgqeq1Znk/GUFn8kPnSzFF3tymtIwix3t2KbRlPuzqwj1ZFUH8sS61JBUJiDWngt0zs1uLAnd80zi7HoM8YgcTgsm5x9/jh+dIwRjWkZuqfNBnc2g8lfi9U+PUq49MxY2anaLpRuWXAoYR7+q8RURVPVuTkYjQOA92mMCbDKiKlbZr0SHnSspk6t8xGGyn4LkoIIxcbHK9ZQINoKKMuDdXKZZScl9W0REQPves5OpwBfmkjCokhEz/VwWx3b/ZYx+lXjbm+XLTBG9dYGKwd7tbgJuLGKfdXrp0qvXZwVS4Q9zpw9ABoHu03kVlRJNMD8UEK6IbZZ1UPRsA9RPHPZZqF8UjKGTMk7YqV/YfD4R6IvjScXkmWfAvUobKvnjwN3yjQsFIUQYMjwsZD3hANEtEGqCDsRSiN3Pd56iX9aU36LbMa5rq53/kYcMFBDkUPUrznI1931OfViG6W0sL6kac6ur5VPKUfEBGSLgFIJzYbYVzpB7hteMYGfkIs+bSVY8tp0cBAKZMNvipE1dEjteIvJec35KYNHQcJGegGokM3p+DplbA9flxW+sH3ZdvkA6XN5FSpT/sUXkXv7xvngDFIrdzVTr/5zoQsYHPEHHpqk5tYry3oOdfkBzs4mnBwRnpeIGGtQMSI49Zs7o=
  app: bbq-finder
  on:
    repo: timkeresey/bbq-finder
