language: node_js
node_js:
- '14'
notifications:
  email: false
deploy:
  provider: heroku
  api_key: M0zMRTRHVqdovpMoRVXyQ5EAsmNc4LS2WtookAD17cGWHNEyTN4o1yYXLIyh8Q49HYsUsqTaNQeKvMk/rF+JeaoQNy8fg2LhtuDgjffGYLh7/NssIQvkOLKBlDccP6SptjyMQvtc8/bitdzzdwX7RlKFcP9DpN2dTn9pHbKF+YsoaF+eKiTEA7II0phl8CQXXuOC3CwhP1qPzyQoukL/nctUi4RBxjaZJSiJzL7IZ1WVyWEhOQY/6FCsh3fGLYZ4NeugEvOkujGXYqrfgOcj5isWk1vOXjpz2iM4JAqSrhzCgBVu0gTZV5405696F8nSRBjKnU1IQAL3aFZJGqFzMgaKoFTa47VMGysJRDqby99xHTNLF90wu0kK7VKAlqzEYNSNNUHPn8DfgIblpDbcH/mO+rtqJvTIEM9vK5jQK05a5KI0wt5UoZsZ5GuFEpSsRBXN+GihBawd7cUYGot4XAyAUsECEEf10K5/AHyHzQ2JHnR3BH+RZVonquo1rYrqbcP7FpEqW9AWqImfg8ySzCXhEYCZLW4BpXJ4X66oRXSXq/BseX3jSPBS6sYv+mYW31cYwWJlpFvx5x9phcbM7+y/zsDHSyE+XfBE03POMFx+W+Q74FWV/VbFtcI0RO8JYECGZz9QrO/3GlgA2InPN0Bx9p7qiAb/xdhMDDcemGQ=
  app: bbq-finder
  on:
    repo: timkeresey/bbq-finder
    branch: main
