language: node_js
node_js:
- "14"
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: a3zN8y3CxQXj0ezZ56M34WYzahKypckZcOks6bObNypmO9j3dSFJii5zfAhmAtfuHjSZM+VXxydlK9qcrqzfD0/ujBVUKBEfeSa95NqJtgiz81zkz+Usy8sgv27QaIqosgf/D0/Gp+05UrE4R1xGMqU1NxN0Uq0jIZarBLsLJgCiMs3AFMtjjMc/UMubKT1zodwqE+rgtR14qSbsmBJjPs7dC39BfkvSy40OCLfz8d8UIglsxRmXpMf7l3/Kx8XEnJYBUNLLvZP4GX7VypS9T+l6AF9u+O0tEcBI0PbldiAgP2AerA4bpiELQbhLJmaSOoNNUDrCUyeRtPQ12IDkjf+v9d1iaPfAD10ZfAVojzrUQg2nb59f+To2y9WjOxNufatcLJzqA6Ce6Lpjn1Z/i6z3exwYeuK75VbarrYzw3/bj/elTzCNQo0gV0zeQozMn+PMtKIEvwHP//gyYBXzxq1/M5kIa/6J+AfcZe11/sA42GK+qvlx1cTsF+8vdIYzIGEvY7dkjrmh4R/JTnY1oPPxldk2GexOw3gh9y7MERbopY4Iu27GuoUtjlZEVqdW7awTyLrlDliORRFugW00mDeGVKc1A0YMnTkzRd737VHYlw4ISTqY/buZzRDlYhP/nrsw5l1QVoXjZx9ansVd0XCwcMsC2dZgobVgjMdoHpQ=
  on:
    all_branches: true  
